# Generated by Django 3.2 on 2023-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_cloth',
            field=models.CharField(choices=[('None', 'None'), ('S', 'Small'), ('L', 'Large'), ('XL', 'Extra Large'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42')], default='None', max_length=200),
        ),
    ]
